// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVviST02o_FgfkmpYLf1tiD16Fm21M_fs',
    appId: '1:893616522472:web:36a65794bdf968407d355d',
    messagingSenderId: '893616522472',
    projectId: 'pantherfuneraladmin',
    authDomain: 'pantherfuneraladmin.firebaseapp.com',
    storageBucket: 'pantherfuneraladmin.firebasestorage.app',
    measurementId: 'G-2VCYVC4GHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVXOWe8t0cRsUpvEqVvIKT4rdwcP_XNo0',
    appId: '1:893616522472:android:3541fc94772632fc7d355d',
    messagingSenderId: '893616522472',
    projectId: 'pantherfuneraladmin',
    storageBucket: 'pantherfuneraladmin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHmEEAfx4UISnRbp2glWaLsyMSQGtOqVk',
    appId: '1:893616522472:ios:fc7754cb61f83d457d355d',
    messagingSenderId: '893616522472',
    projectId: 'pantherfuneraladmin',
    storageBucket: 'pantherfuneraladmin.firebasestorage.app',
    iosBundleId: 'com.example.testtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHmEEAfx4UISnRbp2glWaLsyMSQGtOqVk',
    appId: '1:893616522472:ios:fc7754cb61f83d457d355d',
    messagingSenderId: '893616522472',
    projectId: 'pantherfuneraladmin',
    storageBucket: 'pantherfuneraladmin.firebasestorage.app',
    iosBundleId: 'com.example.testtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVviST02o_FgfkmpYLf1tiD16Fm21M_fs',
    appId: '1:893616522472:web:7e5f3a88937b357e7d355d',
    messagingSenderId: '893616522472',
    projectId: 'pantherfuneraladmin',
    authDomain: 'pantherfuneraladmin.firebaseapp.com',
    storageBucket: 'pantherfuneraladmin.firebasestorage.app',
    measurementId: 'G-1N1Q0BY0XR',
  );
}
