import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'screens/welcome.dart';
import 'screens/checkin.dart';
import 'screens/payment_method.dart';
import 'screens/cash.dart';
import 'screens/card.dart';
import 'screens/signature.dart';
import 'screens/confirmation.dart';
import 'screens/admin_stub.dart';
import 'firebase_setup.dart';
import 'dart:async';

// UI‑only demo flag (no terminal integration yet)
const bool kUiDemo = true;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e, st) {
    debugPrint('Firebase init failed: $e');
    debugPrintStack(stackTrace: st);
  }

  runApp(const PantherUIApp());

  // Run the one-time Firestore bootstrapping in the background AFTER the first frame.
  // Comment this out after you've verified the collections exist.
  WidgetsBinding.instance.addPostFrameCallback((_) {
    // Ignore errors so the UI is never blocked by setup.
    unawaited(Future(() async {
      try {
        await setupFirestore();
      } catch (e) {
        debugPrint('setupFirestore error: $e');
      }
    }));
  });
}

// Small helper so we can intentionally ignore a Future without analyzer warnings.
void unawaited(Future<void> future) {}

class PantherUIApp extends StatelessWidget {
  const PantherUIApp({super.key});

  @override
  Widget build(BuildContext context) {
    final scheme = ColorScheme.fromSeed(seedColor: const Color(0xFFB68D40));
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Panther Kiosk (UI Demo)',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: scheme,
        textTheme: GoogleFonts.interTextTheme(),
        visualDensity: VisualDensity.adaptivePlatformDensity,
        pageTransitionsTheme: const PageTransitionsTheme(builders: {
          TargetPlatform.android: CupertinoPageTransitionsBuilder(),
          TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.linux: FadeUpwardsPageTransitionsBuilder(),
          TargetPlatform.windows: FadeUpwardsPageTransitionsBuilder(),
        }),
      ),
      initialRoute: WelcomeScreen.route, // 👈 start here
      routes: {
        WelcomeScreen.route: (_) => const WelcomeScreen(),
        CheckInScreen.route: (_) => const CheckInScreen(),
        PaymentMethodScreen.route: (_) => const PaymentMethodScreen(),
        CashScreen.route: (_) => const CashScreen(),
        CardScreen.route: (_) => const CardScreen(),
        SignatureScreen.route: (_) => const SignatureScreen(),
        ConfirmationScreen.route: (_) => const ConfirmationScreen(),
        AdminStubScreen.route: (_) => const AdminStubScreen(),
      },
    );
  }
}
